# Generated by Django 3.2 on 2021-12-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_alter_userprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_number_vat',
            field=models.CharField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Description'),
        ),
    ]
