# Generated by Django 3.2 on 2021-12-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20211215_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='agree',
            field=models.BooleanField(default='True'),
        ),
    ]
