# Generated by Django 3.2 on 2021-12-11 22:49

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0004_auto_20211211_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, upload_to='images')),
                ('city', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('position', models.TextField(max_length=250)),
                ('overview', models.TextField(max_length=250)),
                ('requirements', models.TextField(max_length=250)),
                ('contact', models.TextField(max_length=250)),
                ('deadline', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('allowed_membership', models.ManyToManyField(to='userprofiles.Membership')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='userprofiles.userprofile')),
                ('industry', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofiles.industry')),
                ('profession', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofiles.profession')),
            ],
        ),
    ]
